[application]

[web.app]

title = "webcalc"

[web.resource]

style = []

script = []

[web.resource.dev]

script = []

[bundle]
identifier = "ru.mkn"
publisher = "Vasily Fedorov"
icon = ["assets/favicon.ico"]

[bundle.windows]
icon_path = "assets/favicon.ico"
