name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Install Dioxus
        run: cargo install dioxus-cli
      - name: Bundle project
        run: dx bundle --release --server --out-dir dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: webcalc-server
          path: dist/webcalc
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Install Dioxus
        run: cargo install dioxus-cli
      - name: Build project
        run: dx bundle --release --out-dir dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: webcalc-web
          path: dist
  deploy-desktop:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-pc-windows-msvc
            toolchain: stable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Install Dioxus
        run: cargo install dioxus-cli
      - name: Bundle project
        run: dx bundle --release --desktop --package-types "msi" --out-dir dist\bundle
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: webcalc-x86_64-windows.msi
          path: dist\bundle\*.msi
